# Generated by Django 4.0.4 on 2022-05-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
