# Generated by Django 3.2.9 on 2022-05-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_shopuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=200),
        ),
    ]
